# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-10 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('dbsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set([('site', 'module_name', 'class_name', 'attribute_name')]),
        ),
    ]
